### ISSUE TITLE
Server should associate name with user

### ISSUE THREAD

**Issue by tammersaleh** [superorbital/cludo#26]
The server should support a `name` field under each `user`, and use that name when logging any action taking by that user.

(obvs, that name isn't used for authentication, but still good for logging/visibility)

``` yaml
# cludod.yaml

server:
  users:
    - name: Billy Bob
      public_key: ssh-rsa aisudpoifueuyrlkjhflkyhaosiduyflakjsdhflkjashdf7898798765489...
      roles:
        ...
```
