### ISSUE TITLE
Question:  What's the use of `default` in the `cludo.yaml` example?

### ISSUE THREAD

**Issue by tammersaleh** [superorbital/cludo#28]
Example yaml given in README:

``` yaml
# cludo.yaml

client:
  default:
    server_url: "https://www.example.com/"
    key_path: "~/.ssh/id_rsa"
    shell_path: "/usr/local/bin/bash"
    roles: ["default"]
```

and corresponding ENV vars like `CLUDO_CLIENT_DEFAULT_SERVER_URL`

Is the intention to be able to select which client to use via a `cludo` command line flag or ENV var?
