### ISSUE TITLE
Replace `default:` with `default_client`

### ISSUE THREAD

**Issue by tammersaleh** [superorbital/cludo#31]
Currently in `cludo.yaml`:

``` yaml
client:
  default:
    server_url: "https://www.example.com/"
```

``` yaml
default_client: superorbital
client:
  superorbital:
    server_url: "https://www.example.com/"
```
