### ISSUE TITLE
scope `roles` by backend

### ISSUE THREAD

**Issue by tammersaleh** [superorbital/cludo#34]
`cludo.yaml`

``` yaml
client:
  default:
...
    roles: ["aws.production", "ssh.production"]
```
