### ISSUE TITLE
new `cludo.yaml` format

### ISSUE THREAD

**Issue by tammersaleh** [superorbital/cludo#36]
### current

``` yaml
profiles:
  superorbital-prod:
    server_url: "https://www.example.com/"
    key_path: "~/.ssh/id_rsa"
    shell_path: "/usr/local/bin/bash"
    roles: ["aws.prod", "ssh.prod"]
  superorbital-dev:
    server_url: "https://www.example.com/"
    key_path: "~/.ssh/id_rsa"
    shell_path: "/usr/local/bin/bash"
    roles: ["aws.dev", "ssh.dev"]
  bigco-dev:
    server_url: "https://www.example.com/"
    key_path: "~/.ssh/id_rsa"
    shell_path: "/usr/local/bin/bash"
    roles: ["aws.dev", "ssh.dev"]
```

#### Server:

``` yaml
server:
    targets:
        prod:
          aws:
            arn: "aws:arn:iam:..."
            session_duration: "20m"
            access_key_id: "456DEF..."
            secret_access_key: "UVW789..."
          ssh:
            ...
        dev:
          aws:
            arn: "aws:arn:iam:..."
            session_duration: "8h"
            access_key_id: "123ABC..."
            secret_access_key: "ZXY098..."
        sean:
        robert:
        qa:
        prod_frontend:
        prod_backend:
        prod_db:
  users:
    - public_key: "ssh-rsa aisudpoifueuyrlkjhflkyhaosiduyflakjsdhflkjashdf7898798765489..."
      targets: ["prod", "dev"]
```

#### User's `~/.cludo/config.yaml`

``` yaml
ssh_key_paths: ["~/.ssh/so_cludo", "~/.ssh/another_cludo"]
```

#### Repo's `cludo.yaml`

``` yaml
target: https://cludo.superorbital.io/prod 
```

#### When in repo:

``` console
$ cludo exec -- subcommand
```

Will connect to `https://cludo.superorbital.io` using each key in `ssh_key_paths` in turn, and request profile `prod`.
