### ISSUE TITLE
Support simpler `cludo.yaml` client configuration

### ISSUE THREAD

**Issue by jmcshane** [superorbital/cludo#52]
Current `~/.cludo/cludo.yaml` format:

```yaml
client:
  key_path: "~/.ssh/my_ssh_key"
  shell_path: "/usr/local/bin/bash"
```

Desired:

``` yaml
ssh_key_paths: ["~/.ssh/so_cludo", "~/.ssh/another_cludo"]
```

The README has already been updated to match this new format (which means it's _currently_ incorrect).

I _think_ that this may also require a new feature (supporting multiple client SSH keys for authentication).  If so, and assuming that's not trivial:

1. break that into a new issue
2. add a validation that causes the CLI to throw an error if this array has more than one key "We don't yet support multiple SSH keys for authentication.  See URL_TO_ISSUE"
