### ISSUE TITLE
Give the users a knowable "identity", associated to their public key

### ISSUE THREAD

**Issue by jmcshane** [superorbital/cludo#53]
Allow for better auditing/logging associated with granting a session

**Comment by tammersaleh** [comment]
I _think_ this can also simplify and clarify the `cludod.yaml` file's `users` section.  Instead of:

``` yaml
users:
- public_key: "ssh-rsa aisudpoifueuyrlkjhflkyhaosiduyflakjsdhflkjashdf7898798765489..."
  targets: ["prod", "dev"]
```

We can have:

``` yaml
users:
  tammer:
    public_key: "ssh-rsa aisudpoifueuyrlkjhflkyhaosiduyflakjsdhflkjashdf7898798765489..."
    targets: ["prod", "dev"]
```

We should update the README as well when we make this change.

**Comment by spkane** [comment]
It would be easier initially to do this:

```yaml
users:
- name: "Tammer Saleh"
  description: "Founder of SuperOrbital"
  public_key: "ssh-rsa aisudpoifueuyrlkjhflkyhaosiduyflakjsdhflkjashdf7898798765489..."
  targets: ["prod", "dev"]
```
