### ISSUE TITLE
Specify other hard-coded ENV vars to set from cludod server

### ISSUE THREAD

**Issue by tammersaleh** [superorbital/cludo#95]
This will allow admin to configure things like the default AWS region.

``` yaml
server:
  targets:
    prod:
      env:
        AWS_REGION: us-west1
      aws:
        arn: "aws:arn:iam:..."
        session_duration: "20m"
        access_key_id: "456DEF..."
        secret_access_key: "UVW789..."
```

``` console
$ cludo run env
...
AWS_REGION=us-west1
```
